format = """
$username in $directory
$git_branch$git_status
$character
"""

[directory]
style = "yellow"
truncation_length = 2

[git_branch]
symbol = "🌿 "

[git_status]
conflicted = "≠"
ahead = "↑"
behind = "↓"
staged = "+"
deleted = "✘"
modified = "~"
untracked = "?"

[character]
success_symbol = "➜"
error_symbol = "✗"
