Section "InputClass"
    Identifier "Logitech Mouse"
    MatchProduct "Logitech PRO X"
    MatchIsPointer "on"
    Driver "libinput"
    Option "AccelProfile" "flat"
    Option "AccelSpeed" "0.5"
EndSection
